version: '2'

services:
    php:
        build: ./docker/php/${PHP_VERSION}
        container_name: php_${PROJECT_NAME}
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:9000:9000'
        links:
            - mysql
            - memcached
        environment:
            PHP_VERSION_NUMBER: ${PHP_VERSION}
        networks:
            - ${PROJECT_NAME}
        restart: always
    web_server:
        build: ./docker/${WEB_SERVER_TYPE}
        container_name: webserver_${PROJECT_NAME}
        depends_on:
            - source
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:80:80'
            - '${INTERFACE}:443:443'
        links:
            - php
        networks:
            - ${PROJECT_NAME}
        restart: always
    mysql:
        build: ./docker/mysql/${MYSQL_VERSION}
#        image: mysql:${MYSQL_VERSION}
        container_name: mysql_${PROJECT_NAME}
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:33061:3306'
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - ${PROJECT_NAME}
        restart: always
    memcached:
        image: memcached:1.5-alpine
        container_name: memcached_${PROJECT_NAME}
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:11211:11211'
        networks:
            - ${PROJECT_NAME}
        restart: always
    source:
        image: alpine:latest
        container_name: source_${PROJECT_NAME}
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/mysql:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - ./data/mysql:/var/lib/mysql
            - ./data/memcached:/var/lib/memcached
            - ${SITE_PATH}:/var/www
            - /etc/localtime:/etc/localtime/:ro
        networks:
            - ${PROJECT_NAME}
networks:
    bitrix:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.0.0/24